import { auth } from "@/lib/auth";
import { db } from "@/lib/db";
import { companyRegistrationLinks, companyRegistrations, users } from "@/lib/db/schema";
import { desc, eq } from "drizzle-orm";
import InvitationsClient from "./InvitationsClient";
import { Check, X, Clock } from "lucide-react";

export default async function InvitationsPage() {
  const session = await auth();
  if (!session?.user || !["mcr", "management_corporation"].includes(session.user.role)) {
    return <div>Unauthorized. MCR permissions required.</div>;
  }

  const baseUrl = process.env.AUTH_URL || process.env.NEXT_PUBLIC_APP_URL || "";
  const invites = await db
    .select({
      id: companyRegistrationLinks.id,
      token: companyRegistrationLinks.token,
      expiresAt: companyRegistrationLinks.expiresAt,
      isUsed: companyRegistrationLinks.isUsed,
      createdAt: companyRegistrationLinks.createdAt,
      companyId: companyRegistrationLinks.usedByCompanyId,
      companyName: companyRegistrations.companyLegalName,
      generatedByName: users.firstName,
    })
    .from(companyRegistrationLinks)
    .leftJoin(companyRegistrations, eq(companyRegistrations.id, companyRegistrationLinks.usedByCompanyId))
    .leftJoin(users, eq(users.id, companyRegistrationLinks.generatedBy))
    .orderBy(desc(companyRegistrationLinks.createdAt));

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: "2rem" }}>
      <InvitationsClient />

      <div style={{ background: "var(--bg-card)", border: "1px solid var(--border-color)", borderRadius: 12, overflow: "hidden" }}>
        <h3 style={{ padding: 24, borderBottom: "1px solid var(--border-color)" }}>Recent Invitations</h3>
        <div className="table-responsive">
          <table className="table">
            <thead>
              <tr>
                <th>Registration Link</th>
                <th>Company</th>
                <th>Status</th>
                <th>Expires At</th>
              </tr>
            </thead>
            <tbody>
              {invites.map(inv => {
                const isExpired = new Date(inv.expiresAt) < new Date();
                const fullLink = `${baseUrl}/company/register?token=${inv.token}`;
                const hasSubmittedRegistration = !!inv.companyId && !inv.isUsed;
                return (
                  <tr key={inv.id}>
                    <td style={{ maxWidth: 420 }}>
                      <div style={{ display: "flex", flexDirection: "column", gap: 6 }}>
                        <code style={{ fontSize: "0.8rem", wordBreak: "break-all" }}>{fullLink}</code>
                        <div style={{ fontSize: "0.75rem", color: "var(--text-muted)" }}>
                          Generated by {inv.generatedByName || "MCR"}
                        </div>
                      </div>
                    </td>
                    <td>{inv.companyName || "Not registered yet"}</td>
                    <td>
                      {inv.isUsed ? (
                        <span style={{ color: "var(--color-success)", display: "flex", gap: 6, alignItems: "center" }}><Check size={14}/> Approved / Closed</span>
                      ) : hasSubmittedRegistration ? (
                        <span style={{ color: "#0ea5e9", display: "flex", gap: 6, alignItems: "center" }}><Check size={14}/> Registration Submitted</span>
                      ) : isExpired ? (
                        <span style={{ color: "var(--color-danger)", display: "flex", gap: 6, alignItems: "center" }}><X size={14}/> Expired</span>
                      ) : (
                        <span style={{ color: "var(--color-warning)", display: "flex", gap: 6, alignItems: "center" }}><Clock size={14}/> Pending</span>
                      )}
                    </td>
                    <td>{new Date(inv.expiresAt).toLocaleString()}</td>
                  </tr>
                );
              })}
              {invites.length === 0 && (
                <tr>
                  <td colSpan={4} style={{ textAlign: "center", padding: 32, color: "var(--text-muted)" }}>No registration links generated yet.</td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
